### PR TITLE
New activation functions

### PR DESCRIPTION
**Pull request by bcvery1**
Partial work towards #2 

 - Added framework for supporting other activation functions
 - Added activation and derivative functions (used formula from https://en.wikipedia.org/wiki/Activation_function - however these did not pass tests, so those tests are currently commented out)
 - Added more tests (coverage ~86%) - will be nearing 100% when the added activation functions are testable
 - Removed broken badge from README
 - Improved comments/docs and some coding style issues
 - Added `Load` function and moved old `Load` to `LoadFrom`, to allow reading from `io.Reader`
 - `Network` now implements the `json.Unmarshal` and `json.Marshal` interfaces

This PR has non-backwards compatible changes, as the repo is <v1.0 should be OK.

This PR has quite a few commented out tests; I do not know if further changes are required to the logic of the NN functions to make the new activation/derivative functions work.  All uncommented tests work, meaning the repo will build again.

### CODE REVIEW

**Comment by bcvery1** [comment]
Ping @Fontinalis - please let me know if this is not useful, or if I have misunderstood any of the fundamentals. Thanks

**Comment by bcvery1** [comment]
Any thoughts on this, @Fontinalis? Please do let me know if this approach is not workable in its' current form, or if there are changes you want made. Thanks

**Comment by bcvery1** [comment]
Ping

**Comment by Fontinalis** [comment]
Hey @bcvery1 , sorry for the late review. It's nicely done and awesome work! Thanks for the contribution!

**Pull request merged**
